##################################################
# Values that must always be provided by the user.
##################################################

# Join token for the cluster.
authToken:
# Address of the teleport proxy with port (usually :3080).
proxyAddr:
# Details of at least one app to be proxied. Example:
# apps:
#  - name: grafana
#    uri: http://localhost:3000
apps:

##################################################
# Values that you may need to change.
##################################################

# Version of teleport image, if different from appVersion in Chart.yaml.
teleportVersionOverride: ""
# When set to true, the agent will skip the verification of proxy TLS
# certificate.
insecureSkipProxyTLSVerify: false

# If true, create & use Pod Security Policy resources
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: false

##################################################
# Values that you shouldn't need to change.
##################################################

# Container image for the agent. Since this runs without the auth_service, we
# don't need the enterprise version.
image: quay.io/gravitational/teleport
# Number of replicas for the agent deployment.
replicaCount: 1
# Name of the Secret to store the teleport join token.
secretName: teleport-app-agent-join-token
