apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  teleport.yaml: |
    teleport:
      auth_token: "/etc/teleport-secrets/auth-token"
      auth_servers: ["{{ required "proxyAddr is required in chart values" .Values.proxyAddr }}"]

    app_service:
      enabled: true
      apps:
      {{- required "'apps' map is required in chart values, see README" .Values.apps | toYaml | nindent 8 }}

    auth_service:
      enabled: false
    ssh_service:
      enabled: false
    proxy_service:
      enabled: false
